In [2]:
import pandas as pd

In [3]:
df=pd.read_excel(r'sample_superstore.xls')

In [4]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 1.6 MB

In [6]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [7]:
df.describe(include='all')

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994,9994,9994,9994,9994,9994,9994,...,9994.000000,9994,9994,9994,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000
unique,NaN,5009,NaN,NaN,4,793,793,3,1,531,...,NaN,4,1862,3,17,1850,NaN,NaN,NaN,NaN
top,NaN,CA-2017-100111,NaN,NaN,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,...,NaN,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope,NaN,NaN,NaN,NaN
freq,NaN,14,NaN,NaN,5968,37,37,5191,9994,915,...,NaN,3203,19,6026,1523,48,NaN,NaN,NaN,NaN
mean,4997.500000,NaN,2016-04-30 00:07:12.259355,2016-05-03 23:06:58.571142,NaN,NaN,NaN,NaN,NaN,NaN,...,55190.379428,NaN,NaN,NaN,NaN,NaN,229.858001,3.789574,0.156203,28.656896
min,1.000000,NaN,2014-01-03 00:00:00,2014-01-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,1040.000000,NaN,NaN,NaN,NaN,NaN,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,NaN,2015-05-23 00:00:00,2015-05-27 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,23223.000000,NaN,NaN,NaN,NaN,NaN,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,NaN,2016-06-26 00:00:00,2016-06-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,56430.500000,NaN,NaN,NaN,NaN,NaN,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,NaN,2017-05-14 00:00:00,2017-05-18 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,90008.000000,NaN,NaN,NaN,NaN,NaN,209.940000,5.000000,0.200000,29.364000
max,9994.000000,NaN,2017-12-30 00:00:00,2018-01-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,99301.000000,NaN,NaN,NaN,NaN,NaN,22638.480000,14.000000,0.800000,8399.976000
std,2885.163629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32063.693350,NaN,NaN,NaN,NaN,NaN,623.245101,2.225110,0.206452,234.260108

In [8]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df.columns=df.columns.str.replace('-','_')

In [9]:
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub_category',
       'product_name', 'sales', 'quantity', 'discount', 'profit'],
      dtype='str')

In [10]:
df['segment'].unique()

<StringArray>
['Consumer', 'Corporate', 'Home Office']
Length: 3, dtype: str

In [11]:
df['ship_mode'].unique()

<StringArray>
['Second Class', 'Standard Class', 'First Class', 'Same Day']
Length: 4, dtype: str

In [12]:
df['region'].unique()

<StringArray>
['South', 'West', 'Central', 'East']
Length: 4, dtype: str

In [13]:
df['category'].unique()

<StringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

In [14]:
df['sub_category'].unique()

<StringArray>
[  'Bookcases',      'Chairs',      'Labels',      'Tables',     'Storage',
 'Furnishings',         'Art',      'Phones',     'Binders',  'Appliances',
       'Paper', 'Accessories',   'Envelopes',   'Fasteners',    'Supplies',
    'Machines',     'Copiers']
Length: 17, dtype: str

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.dtypes

row_id                    int64
order_id                    str
order_date       datetime64[us]
ship_date        datetime64[us]
ship_mode                   str
customer_id                 str
customer_name               str
segment                     str
country                     str
city                        str
state                       str
postal_code               int64
region                      str
product_id                  str
category                    str
sub_category                str
product_name                str
sales                   float64
quantity                  int64
discount                float64
profit                  float64
dtype: object

In [17]:
# Adding new columns

In [18]:
df['profit_margin']=df['profit']/df['sales']

In [19]:
df['shipping_days']=(df['ship_date'] - df['order_date']).dt.days

In [20]:
# time features

In [21]:
df['order_year'] = df['order_date'].dt.year
df['order_month']=df['order_date'].dt.month
df['order_year_month']=df['order_date'].dt.to_period('M').astype(str)

In [22]:
# loss making orders

In [23]:
df['is_loss']=df['profit']<0

In [24]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,sales,quantity,discount,profit,profit_margin,shipping_days,order_year,order_month,order_year_month,is_loss
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,0.1600,3,2016,11,2016-11,False
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,0.3000,3,2016,11,2016-11,False
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,0.4700,4,2016,6,2016-06,False
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,-0.4000,7,2015,10,2015-10,True
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,0.1125,7,2015,10,2015-10,False

In [25]:
df[['sales', 'profit', 'discount', 'quantity']].describe()

# Flag extreme outliers worth knowing about before they skew a Power BI chart
df[df['profit'] < df['profit'].quantile(0.01)][['order_id', 'product_name', 'sales', 'profit', 'discount']]

,order_id,product_name,sales,profit,discount
3,US-2015-108966,Bretford CR4500 Series Slim Rectangular Table,957.5775,-383.0310,0.45
27,US-2015-150630,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,-1665.0522,0.50
125,US-2014-134614,Bevis 44 x 96 Conference Tables,617.7000,-407.6820,0.50
165,CA-2014-139892,Lexmark MX611dhe Monochrome Laser Printer,8159.9520,-1359.9920,0.40
169,CA-2014-139892,Kensington 7 Outlet MasterPiece Power Center,177.9800,-453.8490,0.80
...,...,...,...,...,...
9480,CA-2014-126193,Ibico Hi-Tech Manual Binding System,304.9900,-533.7325,0.80
9592,US-2016-105452,"Tenex Chairmat w/ Average Lip, 45"" x 53""",302.7200,-378.4000,0.60
9639,CA-2015-116638,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.6440,-1862.3124,0.40
9673,CA-2016-114867,LG G2,1499.9700,-374.9925,0.40
9774,CA-2014-169019,GBC DocuBind P400 Electric Binding System,2177.5840,-3701.8928,0.80

In [26]:
high_discount = df[df['discount'] >= 0.4]
low_discount = df[df['discount'] < 0.4]

print("Orders with discount >= 40%:")
print("  Count:", len(high_discount))
print("  Avg profit margin:", (high_discount['profit'].sum() / high_discount['sales'].sum() * 100).round(2), "%")

print("Orders with discount < 40%:")
print("  Count:", len(low_discount))
print("  Avg profit margin:", (low_discount['profit'].sum() / low_discount['sales'].sum() * 100).round(2), "%")

Orders with discount >= 40%:
  Count: 1139
  Avg profit margin: -50.04 %
Orders with discount < 40%:
  Count: 8855
  Avg profit margin: 19.93 %

In [27]:
import sqlalchemy
from sqlalchemy import create_engine

# Update these for your setup
server = 'localhost'          # or 'localhost\SQLEXPRESS' if using Express
database = 'SuperstoreDB'
driver = 'ODBC Driver 17 for SQL Server'

# Windows Authentication (most common for local dev)
conn_str = f'mssql+pyodbc://@{server}/{database}?driver={driver.replace(" ", "+")}&trusted_connection=yes'

engine = create_engine(conn_str)

df.to_sql('orders', con=engine, if_exists='replace', index=False)

61